name: Windows Native Build

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

# env:
  # Use the runner's workspace directory with a backslash
  # VCPKG_ROOT: ${{ github.workspace }}\vcpkg
  
jobs:
  build-windows:
    runs-on: windows-2022

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install System Dependencies (pkgconf Host Tool)
      run: |
        choco install  gperf #pkgconfiglite
      shell: powershell

        
    - name: mkdir build/
      run: |
        cd ${{ github.workspace }}
        mkdir build -force

    - name: vcpkg depend-info --x-manifest-pid=vcpkg.json
      if: false
      run: vcpkg depend-info cairo:x64-windows
      
    - name: Localize Vcpkg Binary Cache Directory
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/vcpkg-archives
        # Invalidate cache if vcpkg.json or the workflow configuration changes
        key: vcpkg-${{ runner.os }}-${{ hashFiles('vcpkg.json') }}
        restore-keys: |
          vcpkg-${{ runner.os }}-
          
    - name: Run vcpkg (Installs & Caches Dependencies)
      uses: lukka/run-vcpkg@v11
      env:
        ACTIONS_CACHE_URL: ${{ env.ACTIONS_CACHE_URL }}
        ACTIONS_RUNTIME_TOKEN: ${{ env.ACTIONS_RUNTIME_TOKEN }}
        VCPKG_BINARY_SOURCES: "clear;files,${{ github.workspace }}/vcpkg-archives,readwrite"
      with:
        vcpkgJsonGlob: '**/vcpkg.json'

    - name: Configure CMake
      env:
        ACTIONS_CACHE_URL: ${{ env.ACTIONS_CACHE_URL }}
        ACTIONS_RUNTIME_TOKEN: ${{ env.ACTIONS_RUNTIME_TOKEN }}
        VCPKG_BINARY_SOURCES: "clear;files,${{ github.workspace }}/vcpkg-archives,readwrite"
#        VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
      run: |
        cmake -B build -S . `
          -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake `
          -DVCPKG_TARGET_TRIPLET=x64-windows
        
    - name: Debug vcpkg / cairo
      continue-on-error: true
      run: |
        vcpkg list

    - name: Build Project
      continue-on-error: false
      run: |
        cmake --build build --config Release

    - name: Upload Build Output
      uses: actions/upload-artifact@v4
      continue-on-error: false
      with:
        name: publisher_convert-windows-x64-r${{ github.run_number }}
        path: build/
