name: Windows Native Build

on:
  workflow_dispatch:
    inputs:
      vcpkg_refresh_only:
        description: 'Check to vcpkg install only and save cache'
        type: boolean
        default: false
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  # Use the runner's workspace directory with a backslash
  VCPKG_ROOT: ${{ github.workspace }}\vcpkg
  
jobs:
  build-windows:
    runs-on: windows-2022

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4


    # Step 1: Cache vcpkg artifacts (Keep your existing step)
    - name: Cache vcpkg artifacts
      id: cache-vcpkg
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/vcpkg
        key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json') }}
        restore-keys: ${{ runner.os }}-vcpkg-

    # 1. Clone vcpkg source code if directory is missing
    - name: Clone vcpkg Repository
      if: steps.cache-vcpkg.outputs.cache-hit != 'true'
      run: |
        if (-not (Test-Path -Path "${{ env.VCPKG_ROOT }}")) {
          git clone https://github.com/Microsoft/vcpkg.git "${{ env.VCPKG_ROOT }}"
          cd "${{ env.VCPKG_ROOT }}"
          & "${{ env.VCPKG_ROOT }}\bootstrap-vcpkg.bat"
        }
      shell: pwsh
      
    - name: Install System Dependencies (pkgconf Host Tool)
      run: |
        choco install pkgconfiglite gperf
      shell: powershell

    - name: Downloading Vcpkg 📥
      run: |
        cd ${{ github.workspace }}
        mkdir build -force

    - name: Install System Dependencies via vcpkg
      if: steps.cache-vcpkg.outputs.cache-hit != 'true'
      run: |
        vcpkg install --triplet x64-windows
      shell: cmd

    - name: Configure CMake
      if: ${{ inputs.vcpkg_refresh_only == false }}
      run: |
        cmake -B build -S . `
          -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake `
          -DVCPKG_TARGET_TRIPLET=x64-windows
      shell: pwsh

    - name: Build Executable
      if: ${{ inputs.vcpkg_refresh_only == false }}
      run: |
        cmake --build build --config Release
      shell: pwsh

    - name: Upload Build Output
      if: ${{ inputs.vcpkg_refresh_only == false }}
      uses: actions/upload-artifact@v4
      with:
        name: publisher_convert-windows-x64
        path: build/Release/publisher_convert.exe
